name: Deploy Frontend

on:
  push:
    branches: [main, 'feat/#32'] # 테스트용 브랜치 추가 (테스트 후 제거할 것)

env:
  BUCKET_NAME: "ddcn41v1-frontend"
  AWS_REGION: ap-northeast-2

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: package.json

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Build artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: build-frontend-files
          path: build/
          retention-days: 1
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build artifact download
        uses: actions/download-artifact@v4
        with:
          name: build-frontend-files
          path: build/

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: S3 Upload
        run: |
          aws s3 sync ./build/ s3://${{ env.BUCKET_NAME }} \
            --delete